/**
 * Domain Enums for RWA Tokenization Platform
 */

export enum PropertyType {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  HOSPITALITY = 'HOSPITALITY',
  MIXED_USE = 'MIXED_USE',
  LAND = 'LAND',
}

export enum PropertyStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  TOKENIZATION_PENDING = 'TOKENIZATION_PENDING',
  TOKENIZED = 'TOKENIZED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum DocumentType {
  TITLE_DEED = 'TITLE_DEED',
  VALUATION_REPORT = 'VALUATION_REPORT',
  OWNERSHIP_CERTIFICATE = 'OWNERSHIP_CERTIFICATE',
  TAX_RECORD = 'TAX_RECORD',
  INSURANCE_POLICY = 'INSURANCE_POLICY',
  INSPECTION_REPORT = 'INSPECTION_REPORT',
  LEGAL_AGREEMENT = 'LEGAL_AGREEMENT',
  OFFERING_MEMORANDUM = 'OFFERING_MEMORANDUM',
  SPV_INCORPORATION = 'SPV_INCORPORATION',
}

export enum DocumentVerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum SpvStatus {
  FORMATION = 'FORMATION',
  ACTIVE = 'ACTIVE',
  DISSOLVED = 'DISSOLVED',
  SUSPENDED = 'SUSPENDED',
}

export enum TokenStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  DEPLOYMENT_PENDING = 'DEPLOYMENT_PENDING',
  DEPLOYED = 'DEPLOYED',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  RETIRED = 'RETIRED',
}

export enum TokenStandard {
  ERC3643 = 'ERC-3643',
  ERC20 = 'ERC-20',
  ERC1400 = 'ERC-1400',
}

export enum InvestorType {
  INDIVIDUAL = 'INDIVIDUAL',
  INSTITUTIONAL = 'INSTITUTIONAL',
  FAMILY_OFFICE = 'FAMILY_OFFICE',
  CORPORATE = 'CORPORATE',
}

export enum InvestorStatus {
  ACTIVE = 'ACTIVE',
  PENDING_ONBOARDING = 'PENDING_ONBOARDING',
  RESTRICTED = 'RESTRICTED',
  BLOCKED = 'BLOCKED',
}

export enum AccreditationStatus {
  UNACCREDITED = 'UNACCREDITED',
  ACCREDITED = 'ACCREDITED',
  QUALIFIED_PURCHASER = 'QUALIFIED_PURCHASER',
  EXEMPT = 'EXEMPT',
}

export enum KycVerificationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum WalletVerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  SIGNATURE_VERIFIED = 'SIGNATURE_VERIFIED',
  ONCHAIN_WHITELISTED = 'ONCHAIN_WHITELISTED',
  REVOKED = 'REVOKED',
}

export enum AllocationStatus {
  RESERVED = 'RESERVED',
  SETTLED = 'SETTLED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  ESCROWED = 'ESCROWED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum TransactionType {
  PRIMARY_ISSUANCE = 'PRIMARY_ISSUANCE',
  SECONDARY_TRANSFER = 'SECONDARY_TRANSFER',
  DIVIDEND_PAYOUT = 'DIVIDEND_PAYOUT',
  TOKEN_REDEMPTION = 'TOKEN_REDEMPTION',
  BURN = 'BURN',
  RECOVERY = 'RECOVERY',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REVERTED = 'REVERTED',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PROPERTY_ADMIN = 'PROPERTY_ADMIN',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  LEGAL_OFFICER = 'LEGAL_OFFICER',
  ISSUER = 'ISSUER',
  INVESTOR = 'INVESTOR',
  AUDITOR = 'AUDITOR',
}
